"""Structured planning and deterministic, constraint-safe synthetic row generation."""

from __future__ import annotations

import json
import random
import re
import uuid
from dataclasses import dataclass
from datetime import UTC, date, datetime, time, timedelta
from decimal import ROUND_HALF_UP, Decimal
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from app.config import Settings
from app.schema import Column, Schema, Table

DEFAULT_ROW_COUNT = 1_000
MIN_ROW_COUNT = 1
MAX_ROW_COUNT = 10_000
RETRY_BUDGET = 100

SemanticCategory = Literal[
    "identifier",
    "name",
    "email",
    "phone",
    "address",
    "text",
    "number",
    "boolean",
    "date",
    "time",
    "timestamp",
    "uuid",
    "json",
    "binary",
]


class ColumnProfile(BaseModel):
    """A constrained per-column instruction returned by the planning model."""

    model_config = ConfigDict(extra="forbid")

    semantic_category: SemanticCategory
    parameters: dict[str, str | int | float | bool] = Field(default_factory=dict)
    allow_null: bool
    rationale: str = Field(min_length=1, max_length=500)


class GenerationProfile(BaseModel):
    """Validated model response. Every uploaded table and column is required."""

    model_config = ConfigDict(extra="forbid")

    tables: dict[str, dict[str, ColumnProfile]]


@dataclass(frozen=True)
class GenerationReport:
    requested_rows: dict[str, int]
    generated_rows: dict[str, int]
    seed: int
    used_fallback_profile: bool
    warnings: tuple[str, ...]
    validation_errors: tuple[str, ...]
    model: str | None = None
    prompt_metadata: dict[str, Any] | None = None


@dataclass(frozen=True)
class GeneratedDataset:
    rows: dict[str, tuple[dict[str, Any], ...]]
    profile: GenerationProfile
    report: GenerationReport


class GenerationError(ValueError):
    """A schema constraint cannot be satisfied within the bounded retry budget."""


def generation_profile_json_schema() -> dict[str, Any]:
    """Return the response schema passed to Gemini structured-output requests."""

    return GenerationProfile.model_json_schema()


def local_generation_profile(schema: Schema) -> GenerationProfile:
    """Build conservative type/name-based profiles without network or model access."""

    return GenerationProfile(
        tables={
            table.name: {
                column.name: ColumnProfile(
                    semantic_category=_infer_category(column),
                    allow_null=column.nullable,
                    rationale="Deterministic local profile inferred from the column name and type.",
                )
                for column in table.columns
            }
            for table in schema.tables
        }
    )


def parse_generation_profile(schema: Schema, payload: str | dict[str, Any]) -> GenerationProfile:
    """Validate model JSON and ensure it exactly covers the submitted schema."""

    try:
        profile = (
            GenerationProfile.model_validate_json(payload)
            if isinstance(payload, str)
            else GenerationProfile.model_validate(payload)
        )
    except ValidationError as error:
        raise GenerationError("Generation profile is not valid structured output.") from error
    expected_tables = {table.name for table in schema.tables}
    if set(profile.tables) != expected_tables:
        raise GenerationError("Generation profile must contain exactly the uploaded tables.")
    for table in schema.tables:
        expected_columns = {column.name for column in table.columns}
        if set(profile.tables[table.name]) != expected_columns:
            raise GenerationError(
                f"Generation profile for '{table.name}' must contain exactly its columns."
            )
        for column in table.columns:
            item = profile.tables[table.name][column.name]
            if item.allow_null and not column.nullable:
                raise GenerationError(
                    f"Generation profile cannot allow nulls for '{table.name}.{column.name}'."
                )
    return profile


def request_generation_profile(
    schema: Schema, instructions: str, settings: Settings | None
) -> tuple[GenerationProfile, bool, str | None, dict[str, Any]]:
    """Ask Gemini for a profile, falling back safely when configuration or output fails.

    Individual data rows are deliberately never sent to or generated by the model.
    """

    metadata = {"instruction_length": len(instructions), "table_count": len(schema.tables)}
    fallback = local_generation_profile(schema)
    if settings is None:
        return fallback, True, None, metadata
    try:
        from google import genai
        from google.genai import types

        client = genai.Client(
            vertexai=True,
            project=settings.google_cloud_project,
            location=settings.google_cloud_location,
        )
        response = client.models.generate_content(
            model=settings.gemini_model,
            contents=(
                "Create a generation profile for this PostgreSQL schema. Return only JSON matching "
                "the supplied response schema. Do not generate rows. User instructions: "
                f"{instructions}\nSchema: {_schema_summary(schema)}"
            ),
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_json_schema=generation_profile_json_schema(),
            ),
        )
        return (
            parse_generation_profile(schema, response.text),
            False,
            settings.gemini_model,
            metadata,
        )
    except Exception:  # Network/model errors must not prevent local, validated generation.
        return fallback, True, settings.gemini_model, metadata


def generate_dataset(
    schema: Schema,
    *,
    row_counts: dict[str, int] | None = None,
    seed: int | None = None,
    profile: GenerationProfile | None = None,
    instructions: str = "",
    settings: Settings | None = None,
) -> GeneratedDataset:
    """Generate and validate every record before it is eligible for persistence."""

    counts = _validated_row_counts(schema, row_counts)
    actual_seed = seed if seed is not None else random.SystemRandom().randrange(0, 2**63)
    rng = random.Random(actual_seed)
    used_fallback = False
    model: str | None = None
    metadata: dict[str, Any] | None = None
    if profile is None:
        profile, used_fallback, model, metadata = request_generation_profile(
            schema, instructions, settings
        )
    else:
        profile = parse_generation_profile(schema, profile.model_dump())

    rows: dict[str, list[dict[str, Any]]] = {}
    for table in schema.tables:
        table_rows: list[dict[str, Any]] = []
        unique_keys = _local_unique_keys(table)
        seen_keys: dict[tuple[str, ...], set[tuple[Any, ...]]] = {key: set() for key in unique_keys}
        for index in range(counts[table.name]):
            for _ in range(RETRY_BUDGET):
                row = _generate_row(table, index, rng, profile.tables[table.name])
                values = {key: tuple(row[name] for name in key) for key in unique_keys}
                if all(
                    any(item is None for item in value) or value not in seen_keys[key]
                    for key, value in values.items()
                ):
                    table_rows.append(row)
                    for key, value in values.items():
                        if all(item is not None for item in value):
                            seen_keys[key].add(value)
                    break
            else:
                raise GenerationError(
                    f"Unable to generate a unique row for '{table.name}' "
                    f"after {RETRY_BUDGET} attempts."
                )
        rows[table.name] = table_rows
    _assign_foreign_keys(schema, rows, rng)
    frozen_rows = {name: tuple(table_rows) for name, table_rows in rows.items()}
    errors = validate_dataset(schema, frozen_rows)
    if errors:
        raise GenerationError("Generated data failed validation: " + "; ".join(errors))
    report = GenerationReport(
        requested_rows=counts,
        generated_rows={name: len(table_rows) for name, table_rows in frozen_rows.items()},
        seed=actual_seed,
        used_fallback_profile=used_fallback,
        warnings=("Gemini profile unavailable or invalid; local type-based profile used.",)
        if used_fallback
        else (),
        validation_errors=(),
        model=model,
        prompt_metadata=metadata,
    )
    return GeneratedDataset(frozen_rows, profile, report)


def validate_dataset(
    schema: Schema, rows: dict[str, tuple[dict[str, Any], ...]]
) -> tuple[str, ...]:
    """Apply the same schema rules used as the pre-persistence validation gate."""

    errors: list[str] = []
    for table in schema.tables:
        table_rows = rows.get(table.name)
        if table_rows is None:
            errors.append(f"Missing generated table '{table.name}'.")
            continue
        for index, row in enumerate(table_rows):
            for column in table.columns:
                value = row.get(column.name)
                if value is None and not column.nullable:
                    errors.append(f"{table.name}[{index}].{column.name} is required.")
                elif value is not None and not _value_matches_type(value, column):
                    errors.append(f"{table.name}[{index}].{column.name} violates type bounds.")
                if value is not None and not _checks_pass(column.checks, row):
                    errors.append(
                        f"{table.name}[{index}].{column.name} violates a CHECK constraint."
                    )
            if not _checks_pass(table.checks, row):
                errors.append(f"{table.name}[{index}] violates a table CHECK constraint.")
        if table.primary_key:
            values = [tuple(row.get(column) for column in table.primary_key) for row in table_rows]
            if any(any(value is None for value in item) for item in values):
                errors.append(f"{table.name} key {table.primary_key} contains null values.")
            if len(values) != len(set(values)):
                errors.append(f"{table.name} key {table.primary_key} is not unique.")
        for unique in table.unique_constraints:
            values = [tuple(row.get(column) for column in unique.columns) for row in table_rows]
            non_null_values = [value for value in values if all(item is not None for item in value)]
            if len(non_null_values) != len(set(non_null_values)):
                errors.append(f"{table.name} key {unique.columns} is not unique.")
    for table in schema.tables:
        for foreign_key in table.foreign_keys:
            target_rows = rows.get(foreign_key.referenced_table, ())
            targets = {
                tuple(row.get(name) for name in foreign_key.referenced_columns)
                for row in target_rows
            }
            for index, row in enumerate(rows.get(table.name, ())):
                values = tuple(row.get(name) for name in foreign_key.columns)
                if all(value is None for value in values):
                    continue
                if any(value is None for value in values) or values not in targets:
                    errors.append(
                        f"{table.name}[{index}] violates foreign key {foreign_key.columns}."
                    )
    return tuple(errors)


def _validated_row_counts(schema: Schema, overrides: dict[str, int] | None) -> dict[str, int]:
    overrides = overrides or {}
    unknown = set(overrides) - {table.name for table in schema.tables}
    if unknown:
        raise GenerationError(
            f"Row-count overrides name unknown tables: {', '.join(sorted(unknown))}."
        )
    counts = {table.name: overrides.get(table.name, DEFAULT_ROW_COUNT) for table in schema.tables}
    invalid = [
        name
        for name, count in counts.items()
        if not isinstance(count, int) or not MIN_ROW_COUNT <= count <= MAX_ROW_COUNT
    ]
    if invalid:
        raise GenerationError(
            f"Row counts must be integers from {MIN_ROW_COUNT} to {MAX_ROW_COUNT}: "
            f"{', '.join(invalid)}."
        )
    return counts


def _local_unique_keys(table: Table) -> tuple[tuple[str, ...], ...]:
    """Return keys whose values are not later replaced by foreign-key assignment."""

    foreign_key_columns = {
        column for foreign_key in table.foreign_keys for column in foreign_key.columns
    }
    keys = (table.primary_key, *(item.columns for item in table.unique_constraints))
    return tuple(key for key in keys if key and not foreign_key_columns.intersection(key))


def _generate_row(
    table: Table, index: int, rng: random.Random, profiles: dict[str, ColumnProfile]
) -> dict[str, Any]:
    row: dict[str, Any] = {}
    for column in table.columns:
        profile = profiles[column.name]
        if column.name in table.primary_key:
            row[column.name] = _primary_value(column, index)
            continue
        for _ in range(RETRY_BUDGET):
            value = _generate_value(column, profile, index, rng)
            if _checks_pass(column.checks, {**row, column.name: value}):
                row[column.name] = value
                break
        else:
            raise GenerationError(
                f"Unable to satisfy checks for '{table.name}.{column.name}' "
                f"after {RETRY_BUDGET} attempts."
            )
    return row


def _assign_foreign_keys(
    schema: Schema, rows: dict[str, list[dict[str, Any]]], rng: random.Random
) -> None:
    for table in schema.tables:
        for foreign_key in table.foreign_keys:
            targets = rows[foreign_key.referenced_table]
            if not targets:
                raise GenerationError(f"Foreign key from '{table.name}' has no target rows.")
            for row in rows[table.name]:
                nullable = all(table.column(name).nullable for name in foreign_key.columns)
                if nullable and rng.random() < 0.1:
                    for name in foreign_key.columns:
                        row[name] = None
                    continue
                target = rng.choice(targets)
                for local, referenced in zip(
                    foreign_key.columns, foreign_key.referenced_columns, strict=True
                ):
                    row[local] = target[referenced]


def _infer_category(column: Column) -> SemanticCategory:
    name = column.name.lower()
    if column.data_type.name == "uuid":
        return "uuid"
    if column.data_type.name in {"json", "jsonb"}:
        return "json"
    if column.data_type.name == "bytea":
        return "binary"
    if "email" in name:
        return "email"
    if "phone" in name:
        return "phone"
    if any(part in name for part in ("name", "first", "last")):
        return "name"
    if "address" in name:
        return "address"
    if column.data_type.name == "boolean":
        return "boolean"
    if column.data_type.name == "date":
        return "date"
    if column.data_type.name.startswith("time"):
        return "time"
    if column.data_type.name.startswith("timestamp"):
        return "timestamp"
    if column.data_type.name in {
        "smallint",
        "integer",
        "bigint",
        "real",
        "double precision",
        "numeric",
    }:
        return "identifier" if name.endswith("id") else "number"
    return "text"


def _primary_value(column: Column, index: int) -> Any:
    if column.data_type.name == "uuid":
        return str(uuid.UUID(int=index + 1))
    return index + 1


def _generate_value(column: Column, profile: ColumnProfile, index: int, rng: random.Random) -> Any:
    if column.nullable and profile.allow_null and rng.random() < 0.1:
        return None
    default = _default_value(column.default, column)
    if default is not None:
        return default
    category, data_type = profile.semantic_category, column.data_type.name
    if category == "email":
        return f"user{index + 1}@example.test"
    if category == "name":
        return f"Sample Name {index + 1}"
    if category == "phone":
        return f"+1-555-{index % 10000:04d}"
    if category == "address":
        return f"{index + 1} Example Street"
    if data_type in {"smallint", "integer", "bigint"}:
        return rng.randint(1, 1_000_000)
    if data_type in {"real", "double precision"}:
        return round(rng.uniform(0, 10000), 4)
    if data_type == "numeric":
        scale = column.data_type.parameters[1] if len(column.data_type.parameters) > 1 else 2
        precision = column.data_type.parameters[0] if column.data_type.parameters else 12
        maximum = (Decimal(10) ** (precision - scale)) - Decimal(1).scaleb(-scale)
        return Decimal(str(rng.uniform(0, float(maximum)))).quantize(
            Decimal(1).scaleb(-scale), rounding=ROUND_HALF_UP
        )
    if data_type in {"character varying", "character"}:
        limit = column.data_type.parameters[0] if column.data_type.parameters else 255
        return f"sample-{index + 1}"[:limit]
    if data_type == "text":
        return f"Synthetic {category} value {index + 1}"
    if data_type == "boolean":
        return bool(rng.getrandbits(1))
    if data_type == "date":
        return date(2020, 1, 1) + timedelta(days=index % 1826)
    if data_type.startswith("time"):
        return time(index % 24, index % 60, index % 60)
    if data_type.startswith("timestamp"):
        value = datetime(2020, 1, 1, tzinfo=UTC) + timedelta(minutes=index)
        return value if data_type.endswith("with time zone") else value.replace(tzinfo=None)
    if data_type == "uuid":
        return str(uuid.UUID(int=rng.getrandbits(128)))
    if data_type in {"json", "jsonb"}:
        return {"index": index + 1, "synthetic": True}
    if data_type == "bytea":
        return f"synthetic-{index + 1}".encode()
    return f"value-{index + 1}"


def _default_value(default: str | None, column: Column) -> Any | None:
    """Convert safe literals; defer other valid SQL expressions to local generators."""

    if not default:
        return None
    text = default.strip().strip("()")
    if text.upper() in {"CURRENT_TIMESTAMP", "NOW()"}:
        return datetime(2020, 1, 1, tzinfo=UTC)
    if text.upper() in {"TRUE", "FALSE"}:
        return text.upper() == "TRUE"
    if re.fullmatch(r"[-+]?\d+(?:\.\d+)?", text):
        return Decimal(text) if column.data_type.name == "numeric" else int(Decimal(text))
    if len(text) >= 2 and text[0] == text[-1] == "'":
        return text[1:-1].replace("''", "'")
    return None


def _value_matches_type(value: Any, column: Column) -> bool:
    name, parameters = column.data_type.name, column.data_type.parameters
    if name in {"smallint", "integer", "bigint"}:
        return isinstance(value, int) and not isinstance(value, bool)
    if name in {"real", "double precision"}:
        return isinstance(value, int | float | Decimal) and not isinstance(value, bool)
    if name == "numeric":
        if not isinstance(value, int | float | Decimal) or isinstance(value, bool):
            return False
        if parameters:
            digits = len(str(Decimal(str(value)).copy_abs()).replace(".", "").lstrip("0")) or 1
            return digits <= parameters[0]
        return True
    if name in {"character varying", "character"}:
        return isinstance(value, str) and (not parameters or len(value) <= parameters[0])
    if name == "text":
        return isinstance(value, str)
    if name == "boolean":
        return isinstance(value, bool)
    if name == "date":
        return isinstance(value, date) and not isinstance(value, datetime)
    if name.startswith("time"):
        return isinstance(value, time)
    if name.startswith("timestamp"):
        return isinstance(value, datetime)
    if name == "uuid":
        try:
            uuid.UUID(str(value))
            return True
        except (ValueError, AttributeError):
            return False
    if name in {"json", "jsonb"}:
        return isinstance(value, dict | list | str | int | float | bool)
    return name != "bytea" or isinstance(value, bytes)


def _checks_pass(checks: tuple[str, ...], row: dict[str, Any]) -> bool:
    return all(_check_passes(check, row) for check in checks)


def _check_passes(check: str, row: dict[str, Any]) -> bool:
    """Evaluate the simple scalar CHECK forms accepted by the generator safely."""
    expression = check.strip().strip("()")
    match = re.fullmatch(
        r'"?([A-Za-z_][\w$]*)"?\s*(<=|>=|<>|!=|=|<|>)\s*(-?\d+(?:\.\d+)?)', expression
    )
    if match:
        value = row.get(match.group(1))
        if value is None:
            return True  # PostgreSQL CHECK passes unknown/null expressions.
        number = Decimal(match.group(3))
        actual = Decimal(str(value))
        operator = match.group(2)
        return {
            ">": actual > number,
            ">=": actual >= number,
            "<": actual < number,
            "<=": actual <= number,
            "=": actual == number,
            "!=": actual != number,
            "<>": actual != number,
        }[operator]
    match = re.fullmatch(
        r'"?([A-Za-z_][\w$]*)"?\s+BETWEEN\s+(-?\d+)\s+AND\s+(-?\d+)', expression, re.I
    )
    if match:
        value = row.get(match.group(1))
        return value is None or int(match.group(2)) <= value <= int(match.group(3))
    return True  # Non-evaluable SQL checks are deferred to PostgreSQL in Step 4.


def _schema_summary(schema: Schema) -> str:
    return json.dumps(
        {
            table.name: {column.name: column.data_type.display_name for column in table.columns}
            for table in schema.tables
        },
        sort_keys=True,
    )
